name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7

      - name: Setup mise
        id: setup-mise
        uses: jdx/mise-action@v2

      - name: Install Dependencies
        id: bun-install
        run: bun install --frozen-lockfile

      - name: Biome Check
        id: biome-check
        run: bun biome check .

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Bundle
        id: bundle
        run: npm run bundle
